### ISSUE TITLE
Support Viber SSL Pinning Bypass?

### ISSUE THREAD

**Issue by buixuanhuan696** [Eltion/Tiktok-SSL-Pinning-Bypass#1]
Do you have to try bypass Viber SSL Pinning? I used 'frida-multiple-unpinning' firda script and i can not.

**Comment by Eltion** [comment]
Hi @buixuanhuan696

Sorry currently I don't plan working on this. If more people need it I'll take a look 🙂

**Comment by tranlam20220101** [comment]
Currently, viber does not publish api convert phone to viber id. So can you unpinning ssl to get it! @Eltion
