### ISSUE TITLE
[Question] ByPass SSL in old versions

### ISSUE THREAD

**Issue by Evil0ctal** [Eltion/Tiktok-SSL-Pinning-Bypass#10]
I tried to use this project to bypass the old version of TikTok APK (version12-16), but all failed, the following is the error.

```console
Created config_file at:  /home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/temp/libgadget.config.so
Created script_file at:  /home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/temp/libsslbypass.js.so

Patching for armeabi-v7a
Downloading firda-gadget-16.0.8-armeabi-v7a.so.xz
[==================================================]

Traceback (most recent call last):
  File "/home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/patch_apk.py", line 287, in <module>
    main()
  File "/home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/patch_apk.py", line 275, in main
    download_frida_gadget(arch)
  File "/home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/patch_apk.py", line 166, in download_frida_gadget
    return extract_frida_gadget(archive_path, arch)
  File "/home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/patch_apk.py", line 142, in extract_frida_gadget
    with open(filepath, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/evil0ctal/Desktop/Tiktok-SSL-Pinning-Bypass/temp/lib/armeabi-v7a/libgadget.so'
```

Is there any way to bypass the old version of SSL?

**Comment by demon071** [comment]
The old TikTok version may not need to bypass SSL, but the old APIs no longer work

**Comment by Evil0ctal** [comment]
Oh I see, cause we are trying to reverse engineering the old api, somehow the old APL will work, but most features don't work anymore, when I try to capture the packet, it will shows network error.

**Comment by Eltion** [comment]
@Evil0ctal you should change this line in `patch_apk.py` script:
```diff
- libs = ["libbytehook.so"]
+ libs = ["libsscronet.so"]
```
After that it should work :)

**Comment by Evil0ctal** [comment]
Great! I will test it out, thank your!

**Comment by Evil0ctal** [comment]
# update:

By change the so file name, the issue had been resolved. Thanks for your help!

@Eltion @demon071

**Comment by Eltion** [comment]
@Evil0ctal  did the SSL pinning bypass work on the old version?

**Comment by Evil0ctal** [comment]
Yes, it worked, but seems like TikTok shutdown the login interface and I can't login now, but the ssl had been bypassed!

**Comment by Eltion** [comment]
Thanks for confirming that!

**Comment by Evil0ctal** [comment]
No problem, thanks again for this great work:)
