### ISSUE TITLE
Why doesn't tiktok work on AVDs?

### ISSUE THREAD

**Issue by rew1nter** [Eltion/Tiktok-SSL-Pinning-Bypass#19]
Does tiktok have any emulator detection? I tried to use this and the original apk on AVD. Both apps start properly and crash after a few seconds.

**Comment by Sasa2023** [comment]
Yes it detect emulators and most important API doesn't work

**Comment by rew1nter** [comment]
I wonder if it could be bypassed with Frida scripting.

Do you mind pointing me to the file path containing this emulator check?

**Comment by didi789** [comment]
Its work on Genymotion, this device:
![image](https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/assets/14198588/6dfc856a-c8e7-4ded-8ba3-9f519a9ca422)

* Install arm translation https://github.com/niizam/Genymotion_A11_libhoudini/
* Add burp cert as root(!)
And then install the app

**Comment by fdciabdul** [comment]
you can try an old version 

![image](https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/assets/31664438/8354709b-5ea6-4bd6-8fa5-73ba6fc9b8c0)

**Comment by rew1nter** [comment]
Older version of Android or tiktok?

**Comment by fdciabdul** [comment]
> Older version of Android or tiktok?

Older version of tiktok

You can use version 14.*

**Comment by brunoaduarte** [comment]
> Its work on Genymotion, this device: ![image](https://user-images.githubusercontent.com/14198588/239767477-6dfc856a-c8e7-4ded-8ba3-9f519a9ca422.png)
> 
> * Install arm translation https://github.com/niizam/Genymotion_A11_libhoudini/
> * Add burp cert as root(!)
>   And then install the app

Can this trick be applied to BlueStacks emulator? Genymotion keeps crashing when I try to run tiktok
