### ISSUE TITLE
[BUG] Broken on latest Tiktok

### ISSUE THREAD

**Issue by TheVisual** [Eltion/Tiktok-SSL-Pinning-Bypass#29]
**Describe the bug**  
Tiktok now uses libttboringssl.so

**Method**  
Both

**App info**
31.3.1

**Device info**
- Model: OnePlus 7 Pro
- Android Version: 11

**Proxy tool**
mitmproxy: v10.0.0

**Logs**
None

**Additional context**
None

**Comment by Eltion** [comment]
Updated the script to work with the new versions.
