### ISSUE TITLE
[BUG]tiktok 31.2.x and later do not work

### ISSUE THREAD

**Issue by ganlnyn0000** [Eltion/Tiktok-SSL-Pinning-Bypass#31]
@Eltion
Hi, First thank you very much for your wonderful job here. 
I got a problem ,versions 31.1.x and earlier work fine, while versions 31.2.x and later do not work. Please help me, thank you very much!

**Comment by Eltion** [comment]
Updated the script to work with the new versions.

**Comment by ganlnyn0000** [comment]
thank you very much!
