### ISSUE TITLE
THANKS.

### ISSUE THREAD

**Issue by muharremp0** [Eltion/Tiktok-SSL-Pinning-Bypass#4]
facebook and tik tok scripts are successful. But a script for snapchat is nowhere to be found. Can you please make ssl pinning bypass script for snapchat?

**Comment by demon071** [comment]
> facebook and tik tok scripts are successful. But a script for snapchat is nowhere to be found. Can you please make ssl pinning bypass script for snapchat?

can you guide me to use script for facebook

**Comment by Eltion** [comment]
@muharremp0 just created a repo for this: https://github.com/Eltion/Snapchat-SSL-Pinning-Bypass :)
