### ISSUE TITLE
[BUG] 35.0.2+ Can no longer find arm64-v8a offset only armeabi-v7a

### ISSUE THREAD

**Issue by VendorAttestation** [Eltion/Tiktok-SSL-Pinning-Bypass#48]
**Describe the bug**  
37.0.1+ Can no longer find arm64-v8a/armeabi-v7a offset

**Method**  
Patched APK

**App info**
 - 37.0.1+
 - Arch: arm64-v8a

**Device info**
Not Needed

**Proxy tool**
Not Needed

**Logs**
```py
Traceback (most recent call last):
  File "/root/Tiktok-SSL-Pinning-Bypass/patch_apk.py", line 323, in <module>
    main()
  File "/root/Tiktok-SSL-Pinning-Bypass/patch_apk.py", line 312, in main
    fcn_offset = find_offset.find_function_from_apk(temp_apk, arch)
  File "/root/Tiktok-SSL-Pinning-Bypass/find_offset.py", line 58, in find_function_from_apk
    return find_function_offset(lib, arch)
  File "/root/Tiktok-SSL-Pinning-Bypass/find_offset.py", line 48, in find_function_offset
    return find_function_arm64(lib)
  File "/root/Tiktok-SSL-Pinning-Bypass/find_offset.py", line 12, in find_function_arm64
    offset = results[0]['offset']
IndexError: list index out of range
```

**Additional context**
None

**Comment by trantrongkim98** [comment]
- Add this line code `results = [x for x in results if x['type'] == "STRN"]` below `results = r2.cmdj('axtj ' + str(offset))` inside this function `find_function_arm64` in `find_offset.py`
- Good Luck and it worked for me

**Comment by TheVisual** [comment]
> * Add this line code `results = [x for x in results if x['type'] == "STRN"]` below `results = r2.cmdj('axtj ' + str(offset))` inside this function `find_function_arm64` in `find_offset.py`
> * Good Luck and it worked for me

Works you should make a PR and get credit for the fix 👍

**Comment by trantrongkim98** [comment]
> > * Add this line code `results = [x for x in results if x['type'] == "STRN"]` below `results = r2.cmdj('axtj ' + str(offset))` inside this function `find_function_arm64` in `find_offset.py`
> > * Good Luck and it worked for me
> 
> Works you should make a PR and get credit for the fix 👍

I created a pull-request at [Here](https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/pull/49)

**Comment by nhunhu3366** [comment]
@trantrongkim98  not working with 36.5.4

**Comment by trantrongkim98** [comment]
Thanks @64chevy, I'll fix it as soon as possible.

**Comment by trantrongkim98** [comment]
I fixed it at here #49

**Comment by trantrongkim98** [comment]
> > Hi all, I fixed it at here #49
> 
> It patches the apk & the libsscronet.so successfuly but SSL pinning doesn't work still for 36.5.4

Have you pulled my branch?

**Comment by trantrongkim98** [comment]
I was changed this line "results = r2.cmdj('/xj 63 65 72 74 5F 63 6F 75 6E 74 00')" and build on version 36.5.4 and it worked well. can you recheck it?

**Comment by trantrongkim98** [comment]
this is my capture's request " https://api-core-boot.tiktokv.com/aweme/v2/feed/?ac=wifi&channel=googleplay&aid=1233&app_name=musical_ly&version_code=360504&version_name=36.5.4"

**Comment by trantrongkim98** [comment]
TikTok updated their handshake algorithm. So far i don't have any solutions for this.

**Comment by Eltion** [comment]
Should be fixed on the new released version

**Comment by Eltion** [comment]
> How do we patch the library only though?

It should be possible to do, not sure if a lot of people need that, if so I can write a script for that

**Comment by VendorAttestation** [comment]
> > How do we patch the library only though?
> 
> It should be possible to do, not sure if a lot of people need that, if so I can write a script for that

Broke on
[37.2.4](https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/tik-tok-including-musical-ly-37-2-4-release/)

**Comment by VendorAttestation** [comment]
![image](https://github.com/user-attachments/assets/85ac6bc5-6585-4e0f-961b-405bbb6d34c4)

also with ur apk cant login

**Comment by VendorAttestation** [comment]
@Eltion Any news?

**Comment by Sasa2023** [comment]
@Eltion @trantrongkim98 I can't patch libsscronet.so of Tiktok version 36.5.4 is this fix working with you for this version?

**Comment by VendorAttestation** [comment]
@Eltion

**Comment by VendorAttestation** [comment]
https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/issues/58
