### ISSUE TITLE
can i use this script on nox emulator?

### ISSUE THREAD

**Issue by DeathRowTools** [Eltion/Tiktok-SSL-Pinning-Bypass#5]
i tried everything to bypass tiktok ssl on nox, nothing works :( 
is there any possible way i can do it, or do i need to buy an android phone. if so please let me know the best version to get or device name
thanks !

**Comment by Eltion** [comment]
This script should do the work: https://gist.github.com/Eltion/d915b31854fb6e740cdcd7d254b1cc81
You can also try the patched apk which should work on nox emulator: https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/releases/download/v26.3.2/tiktok-v26.3.2-x86-arm-translation.apk

**Comment by DeathRowTools** [comment]
sadly same thing happens tiktok just crashes when i try to bypass
![image](https://user-images.githubusercontent.com/91473167/197312561-3da57050-4720-4b3a-8b3a-10b0b7bd8f1d.png)

**Comment by Eltion** [comment]
It is working for me. 

Nox version: 7.0.3.1000-7.1.2700220610
Android version: Android 7(32 bit)
Tiktok version:  26.6.4 [[apkmirror link]](https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/tik-tok-including-musical-ly-26-6-4-release/tiktok-26-6-4-android-apk-download/)
Frida-server: [frida-server-16.0.2-android-x86.xz](https://github.com/frida/frida/releases/download/16.0.2/frida-server-16.0.2-android-x86.xz)

Note that tiktok has no x86 apk release and nox uses some arm translation to make it work and this is the reason why it's not so  stable.

**Comment by DeathRowTools** [comment]
hmm is there any other emu that supports arm so i can bypass tiktok ssl? genymotion not working for some reason
