### ISSUE TITLE
gen-script.py to produce ssl_bypass.js misssing or deleted from version/tag 37 of this library  

### ISSUE THREAD

**Issue by Cryxto** [Eltion/Tiktok-SSL-Pinning-Bypass#56]
By this [Commit b82a742](https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/commit/b82a742dcd0e96bce5b91205902246100c0592be#diff-395b17fa72b5a8cca71102e7138c0b9b72df4be419d76053e4fa892e2ef944ee) , the `gen_script.py` is deleted but in readme frida section it still refer to use the `ssl_bypass.js`  which produced by `gen_script.py`

![image](https://github.com/user-attachments/assets/392cca24-5460-40f7-a3a6-36d6eb5996de)

**Comment by Eltion** [comment]
Great catch, should be fixed with: https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/commit/1640db99964b76e5b63da8c24d28a9f6428d55c5

Thank you!

**Comment by Cryxto** [comment]
Thx you too ~~

**Comment by Cryxto** [comment]
Thx you too ~~
