### ISSUE TITLE
Is this still working ?

### ISSUE THREAD

**Issue by crocogab** [Eltion/Tiktok-SSL-Pinning-Bypass#6]
Does the apk still working ?

**Comment by DATPH4M** [comment]
Working !

**Comment by crocogab** [comment]
Can u send me your apk pls or explain how to do it ?
Mine is not working

**Comment by DATPH4M** [comment]
You Test on on Nox emulator?

**Comment by crocogab** [comment]
> You Test on on Nox emulator?

Nah il used my Phone (samsung a52 non rooted ) and Adb

**Comment by DeathRowTools** [comment]
hey, you need to install adb on your pc first 
then you need to install frida on your pc, and frida-server on your phone like here:  [Example](https://www.youtube.com/watch?v=QfQmqVK8qxI)
after that run the script
frida -U -l .\tiktok-ssl-pinning-bypass.js -f com.zhiliaoapp.musically --no-pause 
or
frida -U -l .\tiktok-ssl-pinning-bypass.js -f com.zhiliaoapp.musically

hope this helps !

**Comment by crocogab** [comment]
> hey, you need to install adb on your pc first then you need to install frida on your pc, and frida-server on your phone like here: [Example](https://www.youtube.com/watch?v=QfQmqVK8qxI) after that run the script frida -U -l .\tiktok-ssl-pinning-bypass.js -f com.zhiliaoapp.musically --no-pause or frida -U -l .\tiktok-ssl-pinning-bypass.js -f com.zhiliaoapp.musically
> 
> hope this helps !

ty but this is using frida and rooted phone
