### ISSUE TITLE
v19.1.3

### ISSUE THREAD

**Issue by Djuk1c** [Eltion/Tiktok-SSL-Pinning-Bypass#8]
For some reason i just cannot patch v19.1.3, no data is going through my proxy (i've installed a user certificate).
No errors are showing up while patching, but the data doesnt go through the proxy.
All of your pre-patched apk's work perfectly.
Could you patch the 19.1.3? I'd appreciate it, thanks!

**Comment by Eltion** [comment]
I created a patched version for it, you can download it here: https://send.vis.ee/download/4081687bcb3b1c40/#imZBf4SoY9LuwJ8BiqQSMg

If you want to create your own patch you'll need to change the following:

```diff
 def extract_libs_for_apk(apk, arch):
-    libs = ["libbytehook.so"]
+    libs = ["libsscronet.so"]
     with ZipFile(apk) as zip_file:
         namelist = zip_file.namelist()
         for lib in libs:
```

**Comment by Djuk1c** [comment]
Awesome, thanks a ton!
